### PR TITLE
Earth Day Hackathon contributions

### PR DESCRIPTION
**Pull request by Chrisk1905**
3 simple changes made to the src/OrcamapSightigsWebElement.js file.

1.  Southern Resident Orcas now have a unique purple icon

2. The addition of a close button to the popup element

3. changed the map width from 500 pixels to 99% of screen size

### CODE REVIEW

**Comment by Chrisk1905** [comment]
deleted the node_modules directory

**Comment by envm92** [comment]
Just need to resolve conflicts, and it will be ready to be merged ! :)

**Comment by Chrisk1905** [comment]
I pulled the recent changes from origin and got rid of merge conflicts. 

It was educational.

**Comment by Chrisk1905** [comment]
@envm92 If there are no more issues, could you merge the pull request? I don't have the ability, as I don't have write access.

**Pull request merged**
